### PR TITLE
Add path routes

### PR DESCRIPTION
**Pull request by thilan-tran**
## New Routes
- `/map/paths` GET: Get all paths
- `/map/nodes` GET: Get all mapNodes
- `/map/paths` POST: Create a path from an array of coordinates [(lat, long)], which automatically creates the first mapNode from the first coordinate and the second mapNode from the last coordinate
  - Will reuse mapNodes  if they already exist in db.
- `/map/paths` DELETE: Delete a path, deleting its associated points but keeping its two terminal nodes
- `/map/nodes` DELETE: Delete a mapNode, which also deletes all paths that have it as one of its terminal nodes

### CODE REVIEW

**Comment by thilan-tran** [comment]
@dvorjackz Should I be writing unit tests?

**Comment by dvorjackz** [comment]
> @dvorjackz Should I be writing unit tests?

Sure if you want, but if you don't have time to that's fine too

**Review by dvorjackz — CHANGES_REQUESTED** [review]

**Comment by dvorjackz** [comment]
LGTM but I think let's delete the /get all path endpoint, also make sure to save your requests in postman.

Feel free to merge yourself after you are done, and see if you can quickly do this before working on the enterprise stuff: https://www.notion.so/uclabruinbot/Get-rid-of-unnecessary-endpoints-a352f4bea99344a08583acdcfd9a2ed0

**Comment by thilan-tran** [comment]
Yup, makes sense for that route to be hidden from the client. I removed it and also simplified the route URLS. (from `/map/paths` to just `/paths`)

**Pull request merged**
